name: Build Portable ComfyUI

on:
  # Removing automatic triggers
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Build portable package
        run: |
          python create_portable_comfyui.py --ci
          
      - name: Get zip filename
        id: get-zip-filename
        run: |
          echo "ZIP_FILE=$(ls anymatix-portable-comfyui-darwin-*.zip)" >> $GITHUB_OUTPUT
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anymatix-portable-comfyui-macos
          path: ${{ steps.get-zip-filename.outputs.ZIP_FILE }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Build portable package
        run: |
          python create_portable_comfyui.py --ci
          
      - name: Get zip filename
        id: get-zip-filename
        run: |
          echo "ZIP_FILE=$(Get-ChildItem -Path anymatix-portable-comfyui-windows-*.zip | Select-Object -ExpandProperty Name)" >> $env:GITHUB_OUTPUT
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anymatix-portable-comfyui-windows
          path: ${{ steps.get-zip-filename.outputs.ZIP_FILE }}

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
          
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
          
  #     - name: Build portable package
  #       run: |
  #         python create_portable_comfyui.py --ci
          
  #     - name: Get zip filename
  #       id: get-zip-filename
  #       run: |
  #         echo "ZIP_FILE=$(ls anymatix-portable-comfyui-linux-*.zip)" >> $GITHUB_OUTPUT
          
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: anymatix-portable-comfyui-linux
  #         path: ${{ steps.get-zip-filename.outputs.ZIP_FILE }}

  create-release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version
        id: get-version
        run: |
          echo "VERSION=$(cat VERSION.txt | tr -d ' %')" >> $GITHUB_OUTPUT
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get-version.outputs.VERSION }}
          tag_name: v${{ steps.get-version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            artifacts/anymatix-portable-comfyui-macos/*
            artifacts/anymatix-portable-comfyui-windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 